version: "3.7"
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9001:9000
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    hostname: minio
    restart: always
    network_mode: bridge
    entrypoint: sh
    command: -c 'mkdir -p /data/mlflow && /usr/bin/minio server /data'
  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_word1
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always
    network_mode: bridge
  mlflow-tracker:
    container_name: mlflow_server
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql
      - minio:minio
    image: mlflow_tracker_server
    build:
      context: ./mlflow_tracker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_URI: postgresql+psycopg2://mlflow:mlflow_word1@postgresql:5432/mlflow-db
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    network_mode: bridge